### ISSUE TITLE
Juypter notebook loading

### ISSUE THREAD

**Issue by anderson-camp** [LeDataSciFi/Discussion#62]
Has anyone else had issues with Jupyter Notebook taking abnormally long to execute the code? For the past couple hours I haven't been able to run anything because it just keeps loading and never produces an output. I even tried going back into older assignments and they won't run either. I tried restarting my computer and reopening the terminal and nothing works.

**Comment by willperacchio** [comment]
So depending on the specifications of your computer, you may start to run into serious performance issues with analyzing some of the larger 10-K’s. Python is not known for being a particularly performant language, and depending on how you’re opening and closing the files, you could be running into memory issues. Is it able to solve things like `1+1` still, or is that also taking forever?

**Comment by gdmiddleton** [comment]
Having the same issue.  Just tried 1+1 and even that takes a significant amount of time to run.  Any fix for this?

**Comment by anderson-camp** [comment]
Even 1 + 1 isn't working. Any suggestions?

**Comment by donbowen** [comment]
I would check out how your CPU/Memory are doing:
- Windows: CTRL+SHIFT+ESC on windows > Performance tab
- Mac: It seems you want to launch "Activity Monitor" [here](https://smallbusiness.chron.com/see-cpu-utilization-macbook-pro-44500.html). Anyone with a mac can check it out. 
- If your memory is running out... (keep reading)

## How much memory should `measure_risks.ipynb` use / run time?

- My laptop (cpu: intel code i7) ran the text search loop in 2 minutes and 1 second. Yours should not take more than, idk, 15 minutes if it's old and 10 minutes if its reasonably new. **If it lasts longer, stop it.** You have a code issue to fix. 
- My total memory/RAM in use never increased by more than 10MB. (My computer's overall memory availability never changed in a noticeable way)

Possible issue: Is your memory being heavily taxed? It shouldn't be **as long as python is only opening one file at a time**. It's probably because you're opening all of the 10-K files and never "closing them", so Python keeps treating them as if they are open. 

Solution: Assuming you call the file `f`, either (1) after you read it, type `f.close()`. or (2) 
```python 
with open(file,'rb') as f:
    # read the file here like you normally do
    # when the "with" block ends, python closes f automatically
```

---

If it's not that, you should be printing info to show where it is when it gets stuck or slows down, and then investigating.

**Comment by anniechabak** [comment]
I had a similar issue earlier tonight so I restarted my computer. It's been running faster since!
