### ISSUE TITLE
Trying to Test Files

### ISSUE THREAD

**Issue by peterschroeter** [LeDataSciFi/Discussion#64]
When trying to test my download 10-ks workbook by deleting the inputs file and edgar/filings/  folders I get the attached error. It would take far too long for me to go through and delete every edgar filing, is there a way around this? I'm trying to delete the folders in jupyter notebook.

![Screenshot (11)](https://user-images.githubusercontent.com/60153699/77268780-5f12c980-6c7d-11ea-9978-9bef77c56437.png)

**Comment by tdinhjason** [comment]
You can navigate to the assignment5 folder in your os instead of in jupyter. Either right click inputs and hit delete or drag and drop the input folder to your trash bin/recycle. 
<img width="431" alt="Screen Shot 2020-03-22 at 8 46 25 PM" src="https://user-images.githubusercontent.com/31483561/77269070-33dcaa00-6c7e-11ea-809e-d479ffecfc43.png">
