### ISSUE TITLE
Cross Validate for Models Q1-Q4?

### ISSUE THREAD

**Issue by willperacchio** [LeDataSciFi/Discussion#82]
Just wondering if you wanted to cross_validate for models Q1-Q4, or if that'll only be for improving our models in part 2. Thanks!

**Comment by donbowen** [comment]
Not for Q1-Q4.

Cross validation is a tool for improving a predictive model's OOS
performance because it helps you reduce a model's variance, but because it
reduces the estimation (training) sample, it necessarily increases bias (it
understands its current data less). Which is worth it for predictive
exercises, but not for relationship exercises/questions like in Q1-Q4.
