### ISSUE TITLE
Issue Pushing Homework

### ISSUE THREAD

**Issue by austinmargs** [LeDataSciFi/Discussion#86]
I am having an issue with pushing my homework folder to Github. Within Anaconda, I have all of my completed homework assignments in the homework folder, which is in my Participation repo. When I try to commit I get this error:  

<img width="954" alt="Screen Shot 2020-04-15 at 6 58 34 PM" src="https://user-images.githubusercontent.com/60153747/79397041-2ba91f00-7f4b-11ea-92a8-7191e8a28eb7.png">

**Comment by DanielFajardoGitHub** [comment]
While I don't know why you're getting an error, the homework folder in the participation repo should contain the files depicted below, rather than our assignments. 
![Screen Shot 2020-04-15 at 7 00 53 PM](https://user-images.githubusercontent.com/60153748/79397210-93f80080-7f4b-11ea-8718-6fed7ff2edd3.png)

**Comment by anderson-camp** [comment]
https://github.com/desktop/desktop/issues/4432

Someone asked the same question on this thread. Few people had nested .git directories which might be your issue

**Comment by austinmargs** [comment]
> While I don't know why you're getting an error, the homework folder in the participation repo should contain the files depicted below, rather than our assignments.
> ![Screen Shot 2020-04-15 at 7 00 53 PM](https://user-images.githubusercontent.com/60153748/79397210-93f80080-7f4b-11ea-8718-6fed7ff2edd3.png)

**Comment by austinmargs** [comment]
Thanks everyone this was very helpful
