### ISSUE TITLE
Regression - Mechanics and Interpretation Lecture Question

### ISSUE THREAD

**Issue by jacyy** [LeDataSciFi/Discussion#93]
Hi all,

I'm confused about how the interpretation matches with the regression output (both shown in the pictures). 

Here is the code the lecture uses:

`sm_ols('lprice ~ lcarat + ideal + lcarat*ideal', data=subsample_of_equal_amounts).fit().summary()`

Thanks!
![regessiontable](https://user-images.githubusercontent.com/9719536/79793917-5fa38c00-831f-11ea-9758-60ed27f0858c.PNG)
![interpretation](https://user-images.githubusercontent.com/9719536/79793927-629e7c80-831f-11ea-823d-b2112cecf577.PNG)

**Comment by sophflan** [comment]
I'm pretty sure if you re-ran the code that the coefficient estimates outputted slightly different numbers than what you had before because you're taking a different subsample of the larger sample in the line before you run the regression. The interpretation would be the same but you would replace 1.47% with 1.5102% then add the coefficient for ideal for the other part

**Comment by donbowen** [comment]
@sophflan is right. The `.sample()` draws a random sample that can change. (Sloppy work by me!) I just updates the lecture so that it has seeds and now it is 1.53%, but you can run it over and over again and get the same answers :)
